version: "3.9"
name: "echo"
services:
  db:
      container_name: mysql
      profiles:
        - "db"
        - "all"
      ports:
        - "3306:3306"
      build:
        context: ./echo/
        dockerfile: dockerfile.mysql
      deploy:
        resources:
          limits:
            memory: "1g"
  app:
      container_name: app
      profiles:
        - "app"
        - "all"
      depends_on:
        - "db"
      ports:
        - "3000:3000"
      build:
        context: ./echo/
        dockerfile: dockerfile.app
      deploy:
        resources:
          limits:
            memory: "1g"
            
  api:
      container_name: api
      profiles:
        - "api"
        - "all"
      ports:
        - "8080:8080"
      depends_on:
        - db
      build:
        context: ./echo/
        dockerfile: dockerfile.api
      deploy:
        resources:
          limits:
            memory: "1g"