FROM archlinux:base-devel as build_api

RUN pacman -Syu --noconfirm && pacman -Sy --noconfirm maven

COPY ./api/ /api/

WORKDIR /api/

RUN mvn clean install package

FROM archlinux:base-devel as api

RUN pacman -Syu --noconfirm && pacman -Sy --noconfirm jdk17-openjdk && mkdir api

WORKDIR /api/

COPY --from=build_api /api/target/projet-0.0.1-SNAPSHOT.jar /api/projet-0.0.1-SNAPSHOT.jar 

CMD java -jar projet-0.0.1-SNAPSHOT.jar